### ISSUE TITLE
Project Proposal To-Do List

### ISSUE THREAD

**Issue by frehlid** [geoffreyyang/dsci100-002-group7#1]
### **Master Checklist**
- [x] **Complete the table.**
- [x] **Visualizations**
- [x] **General editing (grammar, etc)...**
- [x] **Review choices -- add justifications/uncertanties**

**Comment by frehlid** [comment]
### **Visualizations**

- Create frequency polygon visualizations for the 8 relevant variables. (see tutorial 4)

**Comment by pseigo** [comment]
# Table

> Using only training data, summarize the data in at least one table (this is exploratory data analysis). An example of a useful table could be one that reports the number of observations in each class, the means of the predictor variables you plan to use in your analysis and how many rows have missing data. 

...

**Comment by frehlid** [comment]
### **General Editing**

- Do last (spelling/grammar is not something we want to lose points for).
- Run through Grammarly (dieter)

**Comment by geoffreyyang** [comment]
**Review choices, add justifications**

- Say that we're unsure about some things e.g. class imbalance
- Trying with 10-fold cross-validation first and then dropping down if we don't have the computational power

**Comment by pseigo** [comment]
Solved by #2, #3 and commits pushed to main
